drop table if exists bicycle;
drop table if exists customer;

create table customer (
    id              int generated by default as identity  primary key,
    name            varchar(50) not null,
    document_number int not null unique,
    phone_number    int not null unique,
    email           varchar not null unique
);

create table bicycle (
    id int generated by default as identity primary key,
    brand_name      varchar(50) not null,
    model           varchar(50) not null,
    serial_number   int not null unique,
    customer_id     int references Customer(id) on delete set null
);
